version: "2"

linters:
  enable:
    - errcheck
    - gofumpt
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  gofumpt:
    extra-rules: true
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: indent-error-flow
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
  gosec:
    excludes:
      - G115 # integer overflow (too noisy for type conversions)
  staticcheck:
    checks: ["all", "-ST1003"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
        - errcheck

run:
  timeout: 5m
