// cmd/modelfile-gen generates Ollama Modelfiles for namespace and per-repo
// LoRA adapters produced by the training pipeline.
//
// It reads configs/namespaces.yaml and the checkpoints directory, then emits
// one Modelfile per namespace and one per repo adapter:
//
//	modelfiles/<namespace>/Modelfile           — namespace-wide adapter
//	modelfiles/<namespace>/<repo>/Modelfile    — per-repo adapter
//
// Usage:
//
//	modelfile-gen [flags]
//
// Flags:
//
//	-namespaces     path to namespaces.yaml (default: configs/namespaces.yaml)
//	-checkpoints    base path where training outputs live (default: checkpoints)
//	-out            output base directory (default: modelfiles)
//	-namespace      if set, only generate for this namespace
package main

import (
	"flag"
	"log"
	"os"
	"path/filepath"
	"text/template"

	"gopkg.in/yaml.v3"
)

// NamespacesFile mirrors configs/namespaces.yaml.
type NamespacesFile struct {
	Global     GlobalConfig      `yaml:"global"`
	Namespaces []NamespaceConfig `yaml:"namespaces"`
}

// GlobalConfig holds top-level defaults.
type GlobalConfig struct {
	BaseModel    string `yaml:"base_model"`
	Quantization string `yaml:"quantization"`
}

// NamespaceConfig is one namespace entry.
type NamespaceConfig struct {
	Name         string      `yaml:"name"`
	BaseModel    string      `yaml:"base_model"`
	Quantization string      `yaml:"quantization"`
	Repos        []RepoEntry `yaml:"repos"`
}

// RepoEntry is one repo within a namespace.
type RepoEntry struct {
	Label string `yaml:"label"`
	URL   string `yaml:"url"`
}

// modelfileData holds template data for a Modelfile.
type modelfileData struct {
	// FROM: base Ollama model tag or path to a GGUF.
	From string
	// Adapter: path to a GGUF adapter file (empty for base-only models).
	Adapter string
	// Quantization label shown in comments.
	Quantization string
	// SystemPrompt: optional system message injected into every conversation.
	SystemPrompt string
}

// namespaceMF is the template for namespace-level Modelfiles.
var namespaceMF = template.Must(template.New("ns").Parse(`# Namespace adapter Modelfile — generated by modelfile-gen
# Quantization: {{.Quantization}}
FROM {{.From}}
{{- if .Adapter}}
ADAPTER {{.Adapter}}
{{- end}}
{{- if .SystemPrompt}}

SYSTEM """
{{.SystemPrompt}}
"""
{{- end}}

PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"
`))

// repoMF is the template for per-repo adapter Modelfiles.
var repoMF = template.Must(template.New("repo").Parse(`# Per-repo adapter Modelfile — generated by modelfile-gen
# Quantization: {{.Quantization}}
FROM {{.From}}
{{- if .Adapter}}
ADAPTER {{.Adapter}}
{{- end}}
{{- if .SystemPrompt}}

SYSTEM """
{{.SystemPrompt}}
"""
{{- end}}

PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"
`))

func main() {
	namespacesPath := flag.String("namespaces", "configs/namespaces.yaml", "Path to namespaces.yaml")
	checkpointsDir := flag.String("checkpoints", "checkpoints", "Base checkpoints directory")
	outDir := flag.String("out", "modelfiles", "Output base directory")
	nsFilter := flag.String("namespace", "", "Only generate for this namespace")
	flag.Parse()

	nsf, err := loadNamespaces(*namespacesPath)
	if err != nil {
		log.Fatalf("load namespaces: %v", err)
	}

	for _, ns := range nsf.Namespaces {
		if *nsFilter != "" && ns.Name != *nsFilter {
			continue
		}

		baseModel := ns.BaseModel
		if baseModel == "" {
			baseModel = nsf.Global.BaseModel
		}
		quant := ns.Quantization
		if quant == "" {
			quant = nsf.Global.Quantization
		}

		// Namespace-level Modelfile.
		nsGGUF := filepath.Join(*checkpointsDir, ns.Name, "namespace", "model.gguf")
		if err := writeModelfile(
			filepath.Join(*outDir, ns.Name, "Modelfile"),
			namespaceMF,
			modelfileData{
				From:         ggufPathOrOllamaTag(nsGGUF, baseModel),
				Adapter:      adapterPath(nsGGUF),
				Quantization: quant,
			},
		); err != nil {
			log.Printf("namespace=%s modelfile: %v", ns.Name, err)
		}

		// Per-repo Modelfiles.
		for _, repo := range ns.Repos {
			repoGGUF := filepath.Join(*checkpointsDir, ns.Name, "repos", repo.Label, "model.gguf")
			nsGGUF := filepath.Join(*checkpointsDir, ns.Name, "namespace", "model.gguf")

			if err := writeModelfile(
				filepath.Join(*outDir, ns.Name, repo.Label, "Modelfile"),
				repoMF,
				modelfileData{
					From:         ggufPathOrOllamaTag(nsGGUF, baseModel),
					Adapter:      adapterPath(repoGGUF),
					Quantization: quant,
				},
			); err != nil {
				log.Printf("namespace=%s repo=%s modelfile: %v", ns.Name, repo.Label, err)
			}
		}
	}
}

// ggufPathOrOllamaTag returns the GGUF path if it exists, otherwise falls back
// to the Ollama model tag.
func ggufPathOrOllamaTag(path, fallback string) string {
	if _, err := os.Stat(path); err == nil {
		return path
	}
	return fallback
}

// adapterPath returns the adapter path only when the file exists.
func adapterPath(path string) string {
	if _, err := os.Stat(path); err == nil {
		return path
	}
	return ""
}

// writeModelfile renders tmpl with data and writes it to path.
func writeModelfile(path string, tmpl *template.Template, data modelfileData) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}

// loadNamespaces reads and parses the namespaces YAML file.
func loadNamespaces(path string) (*NamespacesFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var nsf NamespacesFile
	if err := yaml.Unmarshal(data, &nsf); err != nil {
		return nil, err
	}
	return &nsf, nil
}
